[package]
name = "evacuation"
version = "0.1.0"
description = "A Tauri App"
authors = [""]
license = ""
repository = ""
default-run = "evacuation"
edition = "2021"
rust-version = "1.77"

[lib]
name = "evacuation_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.6", features = [] }

[dependencies]
serde_json = "1.0.139"
tauri = { version = "2.3.1", features = [] }
tauri-plugin-dialog = "2.2.0"
tauri-plugin-fs = "2.2.0"
pyo3 = { version = "0.25.1", features = ["auto-initialize"] }
evacuation-core = { git = "https://github.com/NikBel3476/evacuation-core.git", rev = "85e556e" }

[dev-dependencies]
insta = { version = "1.42.1", features = ["yaml"] }
rstest = "0.24.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
