[package]
name = "evacuation"
version = "0.1.0"
description = "A Tauri App"
authors = [""]
license = ""
repository = ""
default-run = "evacuation"
edition = "2021"
rust-version = "1.77"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }

[dependencies]
tauri = { version = "1.6.2", features = ["api-all"] }
pyo3 = { version = "0.18.3", features = ["auto-initialize"] }
evacuation-core = { git = "https://github.com/NikBel3476/evacuation-core.git", rev = "db74447" }

[dev-dependencies]
insta = { version = "1.29.0", features = ["yaml"] }
rstest = "0.19.0"

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
