[package]
name = "bim_output"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
bim_tools = { path = "../../../src/bim_tools" }

[lib]
crate-type=["staticlib", "lib"]